version: '3.1'

services:
  web_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WEB_DB
  web:
    build: ./
    command: ./docker-entrypoint.sh
    volumes:
      - ./:/web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web_db

