version: '3.1'

services:

  web_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WEB_DB
  api_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: API_DB

  web:
    build: ./
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/web
    ports:
      - "8000:8000"
    depends_on:
      - web_db
      - api_db

