# Generated by Django 3.0.3 on 2020-02-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HUI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_pole', models.IntegerField()),
                ('TWO_POLE', models.CharField(max_length=3123)),
            ],
        ),
        migrations.CreateModel(
            name='SECONDTEfdasddsaadsaddsfsSTINGPOSTGRESQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_pole', models.IntegerField()),
                ('TWO_POLE', models.CharField(max_length=3123)),
            ],
        ),
        migrations.CreateModel(
            name='TESTdsfsdsdasddsdsadaINGPOSTGRESQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_pole', models.IntegerField()),
                ('TWO_POLE', models.CharField(max_length=3123)),
            ],
        ),
    ]
