# Generated by Django 3.0.3 on 2020-02-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pug',
        ),
    ]
