# Generated by Django 3.0.3 on 2020-03-28 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WEB_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Содержимое комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB_App.Comment', verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
