# Generated by Django 3.0.3 on 2020-04-08 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WEB_App', '0002_notauthuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('good', models.TextField(verbose_name='Товар')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB_App.Picture', verbose_name='Картинка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
