# Generated by Django 3.0.3 on 2020-04-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_App', '0002_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WEB_App.Picture', verbose_name='image'),
        ),
    ]
