# Generated by Django 3.0.3 on 2020-05-03 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_App', '0002_auto_20200429_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintresponse',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Заголовок жалобы'),
            preserve_default=False,
        ),
    ]
