# Generated by Django 3.0.3 on 2020-03-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_App', '0002_childrencomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChildrenComment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
