# Generated by Django 3.0.3 on 2020-03-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_App', '0003_auto_20200328_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='target_good',
            field=models.TextField(null=True, verbose_name='Товар'),
        ),
    ]
