# Generated by Django 3.0.3 on 2020-04-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_App', '0003_ratephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='hash',
            field=models.TextField(null=True, verbose_name='Хэш фото'),
        ),
    ]
