# Generated by Django 3.0.3 on 2020-04-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_App', '0003_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
