# Generated by Django 3.0.3 on 2020-04-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_App', '0004_picture_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='hash',
        ),
    ]
