# Generated by Django 3.0.3 on 2020-04-21 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WEB_App', '0005_remove_picture_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='notauthuser',
            name='hash',
            field=models.TextField(null=True, verbose_name='Хэш фото'),
        ),
        migrations.AddField(
            model_name='notauthuser',
            name='target_good',
            field=models.TextField(null=True, verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='picture',
            name='hash',
            field=models.TextField(null=True, verbose_name='Хэш фото'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
